In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Importing personal modules
import wrangle as w
import functions as f

# turn off pink boxes for demo
import warnings
warnings.filterwarnings("ignore")

In [2]:
#Importing advanced statistics from 2018 - 2022

df_adv18 = pd.read_csv('2018_adv.csv')
df_adv19 = pd.read_csv('2019_adv.csv')
df_adv20 = pd.read_csv('2020_adv.csv')
df_adv21 = pd.read_csv('2021_adv.csv')
df_adv22 = pd.read_csv('2022_adv.csv')

#Importing standard statistics from 2018 - 2022

df_std18 = pd.read_csv('2018_std.csv')
df_std19 = pd.read_csv('2019_std.csv')
df_std20 = pd.read_csv('2020_std.csv')
df_std21 = pd.read_csv('2021_std.csv')
df_std22 = pd.read_csv('2022_std.csv')

In [3]:
df18 = w.drop(df_adv18, df_std18)

In [4]:
df18 = f.new_stat_cols(df18)

In [5]:
df18 = w.obsolete_col_drop(df18)

In [6]:
df18 = w.cleanup(df18)

In [7]:
df18.head()

,Player,Tm,Pos,Int,Cmp%,Comb,PD,FF,FR,TFL,ppdis,TDs
0,Shaquille Leonard+,IND,LB,2,79.2,163,8.0,4.0,2.0,12.0,17.0,0.0
1,Leighton Vander Esch*,DAL,LB,2,80.0,140,7.0,0.0,0.0,2.0,3.0,0.0
2,Antoine Bethea,ARI,DB,0,66.1,121,4.0,1.0,0.0,5.0,16.0,0.0
3,Telvin Smith,JAX,LB,2,76.6,134,2.0,1.0,1.0,4.0,8.0,1.0
4,Lavonte David,TAM,LB,0,80.5,120,2.0,1.0,2.0,13.0,12.5,0.0

In [8]:
df18 = f.player_ratings_cols(df18)

In [9]:
df18.sort_values('ovr_rtg', ascending = False).head(5)

,Player,Tm,Pos,Int,Cmp%,Comb,PD,FF,FR,TFL,ppdis,TDs,DBR,DLR,LBR,ovr_rtg
169,Aaron Donald*+,LAR,DL,0,0.0,59,1.0,4.0,2.0,25.0,110.5,0.0,35.25,225.50,105.625,366.375
134,J.J. Watt*+,HOU,DL,0,50.0,61,4.0,7.0,0.0,18.0,84.0,0.0,2.50,180.25,96.750,279.500
204,Jadeveon Clowney*,HOU,LB,0,0.0,47,1.0,1.0,3.0,16.0,68.0,1.0,38.25,151.75,73.250,263.250
173,Eddie Jackson*+,CHI,DB,6,50.0,51,15.0,2.0,1.0,2.0,2.0,3.0,120.25,48.75,83.250,252.250
211,Khalil Mack*+,CHI,LB,1,75.0,47,4.0,6.0,2.0,10.0,64.5,1.0,3.00,151.50,86.625,241.125

>>>> # 2019 Analysis

In [10]:
df19 = w.drop(df_adv19, df_std19)

In [11]:
df19 = f.new_stat_cols(df19)

In [12]:
df19 = w.obsolete_col_drop(df19)

In [13]:
df19 = w.cleanup(df19)

In [14]:
df19.head()

            Player   Tm Pos  Int  Cmp%  Comb   PD   FF   FR   TFL  ppdis  TDs
0     Budda Baker*  ARI  DB    0  72.7   147  6.0  1.0  1.0   7.0    6.5  0.0
1  Zach Cunningham  HOU  LB    0  77.6   142  2.0  0.0  2.0   7.0    7.0  0.0
2   Blake Martinez  GNB  LB    1  83.8   155  2.0  1.0  0.0   5.0    8.0  0.0
3        Eric Reid  CAR  DB    0  77.1   130  6.0  1.0  2.0   7.0   13.0  0.0
4     Jordan Hicks  ARI  LB    3  78.3   150  6.0  2.0  1.0  11.0   13.5  0.0

In [15]:
df19 = f.player_ratings_cols(df19)

In [16]:
df19.sort_values('ovr_rtg', ascending = False).head(6)

,Player,Tm,Pos,Int,Cmp%,Comb,PD,FF,FR,TFL,ppdis,TDs,DBR,DLR,LBR,ovr_rtg
233,T.J. Watt*+,PIT,LB,2,40.0,55,8.0,8.0,4.0,14.0,92.5,0.0,77.00,206.50,116.125,399.625
291,Aaron Donald*+,LAR,DL,0,0.0,48,2.0,2.0,1.0,20.0,77.5,0.0,25.50,158.25,77.125,260.875
24,Logan Ryan,TEN,DB,4,66.0,113,18.0,4.0,0.0,4.0,17.5,0.0,76.50,70.50,93.375,240.375
149,Stephon Gilmore*+,NWE,DB,6,50.5,53,20.0,0.0,1.0,0.0,0.0,2.0,126.50,31.25,82.250,240.000
139,Shaquil Barrett*,TAM,LB,1,81.8,58,2.0,6.0,0.0,19.0,86.5,0.0,-36.80,181.25,94.875,239.325
164,Chandler Jones*+,ARI,LB,0,90.0,53,5.0,8.0,3.0,11.0,65.0,0.0,-9.75,157.75,84.000,232.000

>>>> # 2020 Analysis

In [17]:
df20 = w.drop(df_adv20, df_std20)

In [18]:
df20 = f.new_stat_cols(df20)

In [19]:
df20 = w.obsolete_col_drop(df20)

In [20]:
df20 = w.cleanup(df20)

In [21]:
df20.Pos.value_counts()

DB    369
DL    300
LB    228
Name: Pos, dtype: int64

In [22]:
df20.head()

            Player   Tm Pos  Int  Cmp%  Comb   PD   FF   FR   TFL  ppdis  TDs
0  Zach Cunningham  HOU  LB    0  86.0   164  2.0  1.0  0.0   7.0   11.0  0.0
1     Roquan Smith  CHI  LB    2  63.3   139  7.0  1.0  1.0  18.0   17.0  0.0
2      Devin White  TAM  LB    0  83.3   140  4.0  1.0  1.0  15.0   36.0  0.0
3   Neville Hewitt  NYJ  LB    0  70.5   134  4.0  1.0  1.0   6.0    9.0  0.0
4     Jordan Poyer  BUF  DB    2  72.9   124  5.0  2.0  0.0   4.0    9.0  0.0

In [23]:
df20 = f.player_ratings_cols(df20)

In [24]:
df20.sort_values('ovr_rtg', ascending = False).head(30)

,Player,Tm,Pos,Int,Cmp%,Comb,PD,FF,FR,TFL,ppdis,TDs,DBR,DLR,LBR,ovr_rtg
161,T.J. Watt*+,PIT,LB,1,50.0,53,7.0,2.0,0.0,23.0,101.0,0.0,3.25,193.75,108.500,305.500
301,Montez Sweat,WAS,DL,1,0.0,45,6.0,2.0,0.0,12.0,51.0,1.0,58.50,112.75,74.000,245.250
214,Za'Darius Smith*,GNB,LB,0,0.0,52,2.0,4.0,2.0,12.0,58.5,0.0,40.50,132.75,66.875,240.125
170,Xavien Howard*+,MIA,DB,10,51.5,51,20.0,1.0,0.0,1.0,1.0,0.0,133.00,18.25,80.000,231.250
349,Chris Jones*,KAN,DL,0,0.0,36,4.0,2.0,0.0,3.0,71.5,0.0,30.00,125.25,73.625,228.875
185,DeForest Buckner+,IND,DL,0,0.0,58,3.0,2.0,1.0,10.0,55.5,0.0,30.75,117.75,65.125,213.625
281,Joey Bosa*,LAC,DL,0,0.0,39,1.0,0.0,1.0,15.0,71.5,0.0,11.25,136.00,65.375,212.625
242,Stephon Tuitt,PIT,DL,0,0.0,45,3.0,2.0,0.0,10.0,59.0,0.0,24.75,115.75,64.500,205.000
219,J.C. Jackson,NWE,DB,9,59.0,40,14.0,0.0,3.0,1.0,1.0,0.0,100.00,24.50,61.250,185.750
86,Troy Hill,LAR,DB,3,70.3,77,10.0,1.0,2.0,1.0,2.0,3.0,52.70,55.25,70.750,178.700
265,Cameron Heyward*,PIT,DL,1,0.0,54,3.0,0.0,0.0,7.0,49.0,0.0,23.25,94.00,58.750,176.000
202,J.J. Watt,HOU,DL,1,80.0,52,7.0,2.0,1.0,14.0,45.0,1.0,-10.25,111.50,73.250,174.500
224,Jason Pierre-Paul*,TAM,LB,2,63.6,55,6.0,4.0,2.0,7.0,35.5,0.0,12.90,94.00,63.375,170.275
256,Chase Young*,WAS,DL,0,66.7,44,4.0,4.0,3.0,10.0,35.5,1.0,0.80,105.25,58.625,164.675
31,Marlon Humphrey*,BAL,DB,1,61.3,82,11.0,8.0,0.0,4.0,8.5,0.0,39.95,61.25,63.375,164.575
310,Daron Payne,WAS,DL,1,0.0,54,4.0,3.0,1.0,7.0,24.0,0.0,48.00,69.50,46.500,164.000
208,Brandon Graham*,PHI,DL,0,0.0,46,0.0,2.0,1.0,13.0,44.0,0.0,15.00,100.50,47.500,163.000
266,Akiem Hicks,CHI,DL,0,0.0,49,1.0,0.0,1.0,7.0,49.5,0.0,11.25,97.50,51.375,160.125
37,Kenny Moore,IND,DB,4,72.3,80,13.0,1.0,0.0,4.0,9.0,1.0,40.95,47.50,71.250,159.700
159,Haason Reddick,ARI,LB,0,82.4,63,4.0,6.0,0.0,15.0,49.5,0.0,-34.40,123.00,69.875,158.475
60,Eric Wilson,MIN,LB,3,69.2,122,8.0,1.0,2.0,8.0,18.0,0.0,11.80,76.50,69.000,157.300
268,Kerry Hyder,SFO,DL,0,0.0,49,0.0,0.0,1.0,10.0,49.5,0.0,6.00,100.50,49.375,155.875
15,Jessie Bates III,CIN,DB,3,54.3,109,15.0,1.0,0.0,2.0,2.0,0.0,51.45,35.25,67.750,154.450
147,James Bradberry*,NYG,DB,3,61.5,54,18.0,2.0,1.0,0.0,0.0,0.0,70.50,23.50,60.000,154.000
67,Minkah Fitzpatrick*+,PIT,DB,4,50.0,79,11.0,1.0,1.0,1.0,0.0,1.0,58.75,34.75,60.250,153.750
26,Deion Jones,ATL,LB,2,74.1,106,6.0,1.0,1.0,9.0,25.5,1.0,-6.60,87.75,71.125,152.275
1,Roquan Smith,CHI,LB,2,63.3,139,7.0,1.0,1.0,18.0,17.0,0.0,-1.05,85.25,68.000,152.200
14,Fred Warner*+,SFO,LB,2,62.3,125,6.0,1.0,2.0,5.0,23.0,0.0,0.70,81.75,67.000,149.450
303,Aaron Donald*+,LAR,DL,0,100.0,45,1.0,4.0,1.0,14.0,70.5,0.0,-70.75,147.00,72.125,148.375
232,Myles Garrett*+,CLE,DL,0,66.7,48,2.0,4.0,2.0,10.0,49.0,0.0,-26.20,115.50,58.750,148.050